# 📘 Full documentation:
# https://github.com/renalreg/.github/blob/main/README.md#python-test-workflow

name: Auto Release

on:
  push:
    branches:
      - $default-branch

  workflow_dispatch:

jobs:
  call-workflow:
    name: Building release branch and updating CHANGELOG.md
    uses: renalreg/.github/.github/workflows/auto_release.yml@main
    secrets: inherit

    # # Optional configuration.
    # # Uncomment and adjust as required.
    #
    # with:
    #
    #   release_type: "python"
    #   # Description: Built in release strategy
    #   # Default: "simple"
