# 📘 Full documentation:
# https://github.com/renalreg/.github/blob/main/README.md#python-test-workflow

name: Conventional PR Title

on:
  pull_request:
    branches: 
      - [$default-branch]

  workflow_dispatch:

jobs:
  call-workflow:
    name: Check PR title meets conventional commit standards
    uses: renalreg/.github/.github/workflows/conventional_pr_title.yml@main
    secrets: inherit
