
name: Dependabot Open Ticket

on:
  pull_request:
    types:
      - opened
    branches:
      - $default-branch

  workflow_dispatch:

jobs:
  call-workflow:
    name: Dependabot Open Ticket
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: write
    uses: renalreg/.github/.github/workflows/dependabot_open_ticket.yml@main
    secrets: inherit

    with:
    
      project_code: ''
      # Description: The Jira project (space) code

      # # Optional configuration.
      # # Uncomment and adjust as required.

      # issue_type:
      #   # Description: The Jira project (space) code        
      #   # Default: Bug
      # component:
      #   # Description: The Jira project (space) code
      #   # Default: Dependabot