name: pull_request_caller

on:
  push:
    branches-ignore:
      - [$default-branch]

  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflow-templates/pull_request.yml
    secrets: inherit
