name: Python Release

on:
  push:
    branches:
      - [$default-branch]

  workflow_dispatch:

jobs:
  call-workflow:
    name: Building release branch and updating CHANGELOG.md
    uses: renalreg/.github/.github/workflow-templates/python_release.yml@main
    secrets: inherit
