name: Python Publish

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  call-workflow:
    name: Publish build to pypi
    uses: renalreg/.github/.github/workflow-templates/python_publish.yml@main
    secrets: inherit
