# 📘 Full documentation:
# https://github.com/renalreg/.github/blob/main/README.md#python-test-workflow

name: Python File Check

on:
  pull_request:
    branches: 
      - $default-branch

  workflow_dispatch:

jobs:
  call-workflow:
    name: Checking for required files
    uses: renalreg/.github/.github/workflows/python_file_checker.yml@main
    secrets: inherit
