name: python_test_caller

on:
  pull_request:
    branches:
      - [$default-branch]

  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflow-templates/python_test.yml
    secrets: inherit
