name: Python Test

on:
  pull_request:
    branches:
      - [$default-branch]

  workflow_dispatch:

jobs:
  call-workflow:
    name: Running python tests
    uses: renalreg/.github/.github/workflows/python_test.yml@main
    secrets: inherit