name: python_release_caller

on:
  push:
    branches:
      - [$default-branch]

  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflow-templates/python_release.yml
    secrets: inherit
