# 📘 Full documentation:
# https://github.com/renalreg/.github/blob/main/README.md#python-test-workflow


name: Python Test

on:
  pull_request:
    branches:
      - $default-branch

  workflow_dispatch:

jobs:
  call-workflow:
    name: Finding TODOs without a ticket identifier
    if: ${{ !startsWith(github.head_ref, 'release-please--') }}
    uses: renalreg/.github/.github/workflows/python_test.yml@main
    secrets: inherit

    # # Optional configuration.
    # # Uncomment and adjust as required.
    #
    # with:
    #
    #   python_versions: '["3.10", "3.11"]'
    #   # Description: Python versions to test against
    #   # Default: lowest supported Python version
    #
    #   os: '["ubuntu-latest", "windows-latest"]'
    #   # Description: Operating systems to run tests on
    #   # Default: ["ubuntu-latest"]
    #
    #   package_manager_command: "pip install poetry"
    #   # Description: Command to install an additional package manager
    #   # Default: ""
    #
    #   install_command: "poetry install --no-interaction"
    #   # Description: Command used to install dependencies
    #   # Default: "pip install -r requirements.txt"
    #
    #   test_command: "poetry run tox"
    #   # Description: Command used to execute the test suite
    #   # Default: "pytest"
    #
    #   org_deps: true
    #   # Description: Boolean, is private repo access required by dependencies
    #   # Default: false
