name: Sync README Badges

on:
  repository_dispatch:
    types: [sync-readme]
  workflow_dispatch:

jobs:
  update-readme:
    uses: renalreg/.github/.github/workflows/reusable_badges.yml@main
    secrets: inherit
    #with:
    #  visibility: "public"   # defaults to "private" if not set
    #  pypi_package_name: "your-pypi-package-name"

# Customise badges by adding a badges.yml at the same level as README.md
#
# badges:
#   - '[![Coverage](https://img.shields.io/codecov/c/github/REPOPATH)](https://codecov.io/gh/REPOPATH)'
#   - 'any other exact badge markdown'
# enable:
#   - 'stars'
#   - 'codecov'
#   - 'forks'
# disable:
#   - 'codecov'
#   - 'issues'
#   - 'dependencies'
#   - 'vulnerabilities'
#   - 'license'
#   - 'stars'
#   - 'forks'