name: Sync README Badges

on:
  repository_dispatch:
    types: [sync-readme]
  workflow_dispatch:

jobs:
  update-readme:
    uses: renalreg/.github/.github/workflows/reusable_badges.yml@main
    secrets: inherit
    #with:
    # pypi_package_name: "pypi package name"

# you can further customise the badges by adding badges.yml with the following at the same location as the readme.md
#badges:
#  - '[![Coverage](https://img.shields.io/codecov/c/github/REPOPATH)](https://codecov.io/gh/REPOPATH)'
#  - 'any other exact badge'
#enable:
#  - ''
#disable:
  #- 'codecov'
  #- 'issues'
  #- 'dependencies'
  #- 'vulnerabilities'
  #- 'license'
  #- 'stars'
  #- 'forks'
  #- 'coverage'



