name: todo_check_caller

on:
  pull_request:
    branches:
      - [$default-branch]

  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflow-templates/todo_check.yml
    secrets: inherit
