name: Check Git Dependency Tags

on:
  workflow_call:

jobs:
  check-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout shared templates
        uses: actions/checkout@v4
        with:
          repository: renalreg/.github
          ref: main
          path: _shared

      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.REN_APP_ID }}
          private-key: ${{ secrets.REN_APP_KEY }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install toml packaging

      - name: Check git dependency tags
        run: |
          python _shared/.github/scripts/check_git_tags.py