name: Python Tester

on:
  push:
  pull_request:
    branches:
      - "**:**"
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    uses: renalreg/ ./github .github/workflows/python_test_gen.yml@additions
    with:
      python_versions: # python versions example python_versions: '3.6, 3.8, 3.9'
    # add extra steps below to run in the same environment as tests
