name: Test

on:
  workflow_call:
    inputs:
      python_versions:
        type: string
        description: 'Comma-separated list of Python versions to use for testing'
        required: true
        default: '["3.6"]'
      use_poetry:
        type: boolean
        description: 'Whether to use Poetry for dependency management and testing defaults to true'
        required: false
        default: true
      use_pip:
        type: boolean
        description: 'Whether to use pip for dependency management and testing (overrides use_poetry)'
        required: false
        default: false
      os:
        type: string
        description: 'Comma-separated list of matrixs'
        required: false
        default: "['ubuntu-20.04']"
      directory_to_scan:
        type: string
        description: 'Directory to scan for TODO comments (defaults to all files)'
        required: false
        default: './'

jobs:
  test:
    name: Run tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        python: ${{ fromJson(inputs.python_versions) }}

    env:
      DIRECTORY_TO_SCAN: ${{ inputs.directory_to_scan }}
      TODO_REGEX: 'TODO:(?!\s*\[[A-Za-z0-9-]+\])'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install and configure Poetry
        if: ${{ inputs.use_poetry && !inputs.use_pip }}
        run: |
          python -m pip install -U pip wheel poetry
          poetry install
          

      - name: Install dependencies with pip
        if: ${{ inputs.use_pip && !inputs.use_poetry }}
        run: |
          python -m pip install --upgrade pip
          pip install tox


      - name: Run tests with Poetry
        if: ${{ inputs.use_poetry && !inputs.use_pip }}
        run: poetry run tox

      - name: Run tests with Tox (pip)
        if: ${{ inputs.use_pip }}
        run: tox

      - name: TODO Check (Linux)
        if: runner.os == 'Linux'
        continue-on-error: true
        run: |
          result=$(find "$DIRECTORY_TO_SCAN" -type f -name "*.py" -exec grep -Hn -P "$TODO_REGEX" {} \;)
          if [ -n "$result" ]; then
            echo "Non-matching TODO comments found:"
            echo "$result"
            exit 1
          fi

      - name: TODO Check (Windows)
        if: runner.os == 'Windows'
        continue-on-error: true
        run: |
          $result = Get-ChildItem -Path $env:DIRECTORY_TO_SCAN -Filter *.py -Recurse | ForEach-Object { Get-Content $_.FullName | Select-String -Pattern $env:TODO_REGEX }
          if ($result) {
            echo "Non-matching TODO comments found:"
            echo "$result"
            exit 1
          }
