name: Test

on:
  workflow_call:
    inputs:
      python_versions:
        type: string
        description: 'Comma-separated list of Python versions to use for testing'
        required: true
        default:  '["3.6"]'

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ${{ fromJson(inputs.python_versions) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install and configure Poetry
        run: python -m pip install -U pip wheel poetry

      - name: Install Dependencies
        run: poetry install

      - name: Run Tox
        run: poetry run tox
